# Generated by Django 2.2.6 on 2019-10-08 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.BigIntegerField(blank=True, null=True)),
                ('customer_id', models.TextField(blank=True, null=True)),
                ('customer_unique_id', models.TextField(blank=True, null=True)),
                ('customer_zip_code_prefix', models.BigIntegerField(blank=True, null=True)),
                ('customer_city', models.TextField(blank=True, null=True)),
                ('customer_state', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'customers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Geolocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.BigIntegerField(blank=True, null=True)),
                ('geolocation_zip_code_prefix', models.BigIntegerField(blank=True, null=True)),
                ('geolocation_lat', models.FloatField(blank=True, null=True)),
                ('geolocation_lng', models.FloatField(blank=True, null=True)),
                ('geolocation_city', models.TextField(blank=True, null=True)),
                ('geolocation_state', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'geolocation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.BigIntegerField(blank=True, null=True)),
                ('order_id', models.TextField(blank=True, null=True)),
                ('order_item_id', models.BigIntegerField(blank=True, null=True)),
                ('product_id', models.TextField(blank=True, null=True)),
                ('seller_id', models.TextField(blank=True, null=True)),
                ('shipping_limit_date', models.TextField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('freight_value', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'order_items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderPayments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.BigIntegerField(blank=True, null=True)),
                ('order_id', models.TextField(blank=True, null=True)),
                ('payment_sequential', models.BigIntegerField(blank=True, null=True)),
                ('payment_type', models.TextField(blank=True, null=True)),
                ('payment_installments', models.BigIntegerField(blank=True, null=True)),
                ('payment_value', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'order_payments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderReviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.BigIntegerField(blank=True, null=True)),
                ('review_id', models.TextField(blank=True, null=True)),
                ('order_id', models.TextField(blank=True, null=True)),
                ('review_score', models.TextField(blank=True, null=True)),
                ('review_comment_title', models.TextField(blank=True, null=True)),
                ('review_comment_message', models.TextField(blank=True, null=True)),
                ('review_creation_date', models.TextField(blank=True, null=True)),
                ('review_answer_timestamp', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'order_reviews',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.BigIntegerField(blank=True, null=True)),
                ('order_id', models.TextField(blank=True, null=True)),
                ('customer_id', models.TextField(blank=True, null=True)),
                ('order_status', models.TextField(blank=True, null=True)),
                ('order_purchase_timestamp', models.TextField(blank=True, null=True)),
                ('order_approved_at', models.TextField(blank=True, null=True)),
                ('order_delivered_carrier_date', models.TextField(blank=True, null=True)),
                ('order_delivered_customer_date', models.TextField(blank=True, null=True)),
                ('order_estimated_delivery_date', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.BigIntegerField(blank=True, null=True)),
                ('product_id', models.TextField(blank=True, null=True)),
                ('product_category_name', models.TextField(blank=True, null=True)),
                ('product_name_lenght', models.FloatField(blank=True, null=True)),
                ('product_description_lenght', models.FloatField(blank=True, null=True)),
                ('product_photos_qty', models.FloatField(blank=True, null=True)),
                ('product_weight_g', models.FloatField(blank=True, null=True)),
                ('product_length_cm', models.FloatField(blank=True, null=True)),
                ('product_height_cm', models.FloatField(blank=True, null=True)),
                ('product_width_cm', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sellers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.BigIntegerField(blank=True, null=True)),
                ('seller_id', models.TextField(blank=True, null=True)),
                ('seller_zip_code_prefix', models.BigIntegerField(blank=True, null=True)),
                ('seller_city', models.TextField(blank=True, null=True)),
                ('seller_state', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sellers',
                'managed': False,
            },
        ),
    ]
