# Generated by Django 2.2.6 on 2019-10-14 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aisles',
            fields=[
                ('aisle_id', models.AutoField(primary_key=True, serialize=False)),
                ('aisle', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'aisles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'departments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('product_id', models.IntegerField()),
                ('add_to_cart_order', models.IntegerField(blank=True, null=True)),
                ('reordered', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'order_products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('order_number', models.IntegerField(blank=True, null=True)),
                ('order_dow', models.IntegerField(blank=True, null=True)),
                ('order_hour_of_day', models.IntegerField(blank=True, null=True)),
                ('days_since_prior_order', models.IntegerField(blank=True, null=True)),
                ('order_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'products',
                'managed': False,
            },
        ),
    ]
